#!/usr/bin/env bash

set -e

DEFAULT_CONFIG_DIR="."
CONFIG_FILE="install.conf.yaml"
DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

for dir in ${DEFAULT_CONFIG_DIR} ${@}; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" --plugin-dir ".plugins/pacaur" -d "${BASEDIR}/${dir}" -c "${dir}/${CONFIG_FILE}"
done