#!/bin/sh

[[ "$(uname -s)" == "Darwin" ]] || exit 0

karabiner="/Applications/Karabiner.app/Contents/Library/bin/karabiner"
seil="/Applications/Seil.app/Contents/Library/bin/seil"

if command -v $karabiner > /dev/null 2>&1; then
    # Finder
    $karabiner set remap.app_finder_switch_open_rename 1

    # Terminal
    $karabiner set remap.app_term_disable_bigger_and_smaller 1
    $karabiner set remap.terminalarrows.appdef 1
else
    echo "Karabiner not installed."
fi

if command -v $seil > /dev/null 2>&1; then
    # Caps lock to escape
    $seil set keycode_capslock 53
else
    echo "Seil not installed."
fi
