#! /bin/sh

SXHKD_SHELL=/bin/bash sxhkd &

for m in $(bspc query --monitors); do
    bspc monitor $m -d web term code misc music
done

bspc config border_width            2
bspc config active_border_color     \#2E3440
bspc config focused_border_color    \#2E3440
bspc config normal_border_color     \#2E3440
bspc config window_gap              12

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true

bspc rule -a Nightly desktop=web
bspc rule -a Firefox desktop=web
bspc rule -a Code desktop=code

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload top &
done
